---
- name: Install Nginx on CentOS
  hosts: localhost
  tasks:
    - name: Install Nginx package installation
      yum:
        name: nginx
        state: present
    - name: nginx service start
      service:
        name: nginx 
        state: started
        enabled: yes
